name: Deploy to production
description: Reload Server
author: Phong Phi

branding: 
  color: blue
  icon: command

inputs: 
  port: 
    description: "Server port"
    required: true
  db_name: 
    description: "Database name"
    required: true
  db_endpoint: 
    description: "database endpoint"
    required: true
  db_username:
    description: "Database authentication username"
    required: true
  db_password:
    description: "Database authentication password"
    required: true
  jwt_key:
    description: "Jwt key for validate"
    required: true
runs: 
  using: composite
  steps: 
    - name: Restart Server
      shell: bash
      env: 
        NODE_ENV: production
        PORT: ${{ inputs.port }}
        DB_NAME: ${{ inputs.db_name }}
        DB_ENDPOINT: ${{ inputs.db_endpoint }}
        DB_USERNAME: ${{ inputs.db_username }}
        DB_PASSWORD: ${{ inputs.db_password }}
        JWT_KEY: ${{ inputs.jwt_key }}
      run: pm2 restart all