name: Deploy to production
description: Copy build files to serve folder
author: Phong Phi
branding: 
  color: blue
  icon: command
inputs:
  production_destination: 
    description: "Production serve static files destination"
    required: true
  repository: 
    description: "Build repository"
    required: true
runs: 
  using: composite
  steps: 
    - name: Deploy to production
      shell: bash
      run: cp ${{ inputs.repository }}/build ${{ inputs.production_destination }} -r