name: Deploy production videosdk

on:
  push:
    branch:
      - "main"
    paths:
      - "videosdk/**"

jobs:
  deploy-web:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Build main branch, confirgured to use production server
        uses: ./.github/actions/build
        with:
          generate_sourcemap: false
          repository: videosdk
          sdk_api_key: ${{ secrets.SDK_API_KEY }}

      - name: Deploy to production
        uses: ./.github/actions/deploy
        with:
          repository: videosdk
          production_destination: "/var/www/dr-health-videosdk"
