name: Deploy production client

on:
  push:
    branch:
      - "main"
    paths:
      - "client/**"

jobs:
  deploy-client:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          repository: client

      - name: Build main branch, confirgured to use production server
        uses: ./.github/actions/build
        with:
          generate_sourcemap: false
          repository: client
          websocket_server_hostname: "wss://dr-health.com.vn/graphql"
          api_server_hostname: "https://dr-health.com.vn/graphql"

      - name: Deploy to production
        uses: ./.github/actions/deploy
        with:
          repository: client
          production_destination: "/var/www/dr-health"
