name: Deploy production server

on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"

jobs:
  deploy-server:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: './client/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('./server/yarn.lock') }}

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          repository: server
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Reload Production Server
        uses: ./.github/actions/restart
        with:
          port: ${{ secrets.SERVER_PORT }}
          db_name: ${{ secrets.DB_NAME }}
          db_endpoint: ${{ secrets.DB_ENDPOINT }}
          db_username: ${{ secrets.DB_USERNAME }}
          db_password: ${{ secrets.DB_PASSWORD }}
          jwt_key: ${{ secrets.JWT_KEY }}
          server_name: ${{ secrets.SERVER_NAME }}