name: Deploy production server

on:
  push:
    branch:
      - "main"
    path:
      - "/server/**"

jobs:
  deploy-server:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Reload Production Server
        uses: ./.github/actions/restart