name: Deploy production web

on:
  push:
    branch:
      - "main"
    paths:
      - "web/**"

jobs:
  deploy-web:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Build main branch, confirgured to use production server
        uses: ./.github/actions/build
        with:
          generate_sourcemap: false
          repository: web
          websocket_server_hostname: "wss://dr-health.com.vn/graphql"
          api_server_hostname: "https://dr-health.com.vn/graphql"

      - name: Deploy to production
        uses: ./.github/actions/deploy
        with:
          repository: web
          production_destination: "/var/www/dr-health-web"
